---
#title: "InitialReviewOfRawData"
#author: "Richard Paterson"
#date: "May 5, 2019"
#course: IST 707 Data Analytics Final Project"
---

## The objective of this code os to review and understand the source data


```{r setup, include=TRUE}

#install.packages("nnet")

knitr::opts_chunk$set(echo = FALSE)
## ONCE: install.packages("wordcloud")
library(wordcloud)
#install.packages('tm')
library(tm)
library(stringr)
#install.packages("SnowballC")
library(SnowballC)
## ONCE: install.packages("slam")
library(slam)
library(cluster)
#library(rsq, quietly=T)
#library(plyr, quietly=T)
library(dplyr, quietly=T)
#library(sqldf, quietly=T)
#library(ggplot2, quietly=T)
#library(stats, quietly=T)
#library(reshape2, quietly=T)
library(RWeka, quietly=T)
#install.packages("partykit") #once only
#library(partykit)
#using numerically converted attributes (sans churn column)
#install.packages("factoextra")
library(factoextra)
#install.packages("stringr") # once only
library(stringr)
#library(stringi, quietly=T)
#e1071 for svm
#install.packages("e1071")
#library(e1071)
# for randomFOrest
#library(randomForest)
# https://www.rdocumentation.org/packages/kernlab/versions/0.9-27/topics/ksvm
#library(kernlab, quietly=T) #ksvm
```

# IST 707 - Data Analytics Final Project


```{r readindata}

cat ('FP : Start')

setwd('C:/Users/Richpat/Documents/@syracuse coursework/@IST 707 Data Analytics (R)/finalproject')

#Read the data in

InFile="./ted-talks/ted_main.csv"
tedmain<-read.csv(InFile, sep=",", na.string=c(""))
str(tedmain)
summary(tedmain)

InFile="./ted-talks/transcripts.csv"
tedtranscripts<-read.csv(InFile, sep=",", na.string=c(""))
str(tedtranscripts)
summary(tedtranscripts)

```

# END
